### ISSUE TITLE
No module named 'tutorial_utils'

### ISSUE THREAD

**Issue by LucasViktor** [PyFstat/PyFstat#546] opened 2023-12-07 15:54 UTC
**Describe the bug**
I'm trying to run the examples, but even with the installation being successful, the library is not being found.
Error: No module named 'tutorial_utils'

**Expected behavior**
If possible, summarize the intended behavior you expected to get.

**Environment (please complete the following information):**
- What OS are you using?
- What sort of virtual environment (if any) are you using? How did you create it? Please attach command if possible.
- Please attach output of `pip list`, `conda list` or equivalent.
- How did you install PyFstat? Please attach command if possible.

**To Reproduce**
Steps to reproduce the behavior. Please be as specific as possible.
The more you tell us about what you did, the easier it will be to get it fixed :) .

**Additional context**

**Comment by dbkeitel** [comment] 2023-12-08 15:25
Hi @LucasViktor how did you obtain the tutorial notebooks- are you working on a complete git clone / dowload of the full repo directories, or did you just download the individual .ipynb files? If the latter, then the solution could be as simple as downloading https://github.com/PyFstat/PyFstat/blob/master/examples/tutorials/tutorial_utils.py into the same directory.

If that's not sufficient, how have you installed: conda, pip, from source...?  If you fill out the questions from the issue template, then it's easier to help.

**Comment by dbkeitel** [comment] 2023-12-12 15:59
Hi @LucasViktor please also check these notes on running notebooks from conda envs: https://github.com/PyFstat/PyFstat/wiki/conda-environments#enabling-jupyter-notebooks - however your symptom is different, so just making sure you run the notebook from the right directory that also includes the tutorial_utils.py should hopefully be enough.

**Comment by dbkeitel** [comment] 2024-06-28 21:19
Closing since there hasn't been info for reproducibility given in a long while. Please let us know again if you encounter any issues.

**Closed by dbkeitel** 2024-06-28 21:19 UTC
Labels: bug, examples
